# Generated by Django 5.1.4 on 2026-08-15 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('expiry_date', models.DateField(db_index=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('expired_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('exhausted', 'Exhausted')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='medicine.medicine')),
                ('purchase_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batch', to='purchase.purchaseitem')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('expiry', 'Expiry'), ('purchase_return', 'Purchase Return'), ('customer_return', 'Customer Return')], db_index=True, max_length=30)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.inventorybatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='medicine.medicine')),
            ],
            options={
                'db_table': 'inventory_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['medicine', 'status'], name='inventory_b_medicin_3245fe_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['batch_number'], name='inventory_b_batch_n_6c5580_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='inventory_b_medicin_647aed_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['medicine', 'created_at'], name='inventory_l_medicin_f939e5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['movement_type'], name='inventory_l_movemen_b76e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['reference_id'], name='inventory_l_referen_e458d4_idx'),
        ),
    ]
