# Generated by Django 5.1.4 on 2026-08-15 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('generic_name', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('drops', 'Drops'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('gel', 'Gel'), ('powder', 'Powder'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('other', 'Other')], default='tablet', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('storage_instruction', models.CharField(blank=True, default='', max_length=255)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicine',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['barcode'], name='medicine_barcode_fc3622_idx'), models.Index(fields=['name'], name='medicine_name_b062d1_idx'), models.Index(fields=['generic_name'], name='medicine_generic_b05b8f_idx'), models.Index(fields=['status'], name='medicine_status_d7e6a7_idx')],
            },
        ),
    ]
