# Generated by Django 5.1.4 on 2026-08-15 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('gst_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('drug_license_number', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='supplier_name_b57b10_idx'), models.Index(fields=['mobile'], name='supplier_mobile_d23a6a_idx'), models.Index(fields=['gst_number'], name='supplier_gst_num_91be4a_idx'), models.Index(fields=['status'], name='supplier_status_250ebc_idx')],
            },
        ),
    ]
